# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fc0c189694d70acd50db64b89ca28af418a1f0ee206de8e240033865d70333fb943d40cba6394688c524f3540ffa683efe042efc50c249d3d2cde3eba8af382

test:
  secret_key_base: 27e88568dac85fae705403632d6c90cb8a74c73f140a7ce585f5aba8aa1395bbac023bdf697d4f88127f8eb3a1aecc9316bdf3af437118f52a9ad7949663ca3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
